[package]
name = "rs-sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_serde = "0.1.0"
scanf = "1.2.1"


[dev-dependencies]
assert_cmd = "2.0.11"
